In [2]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.array(range(0, 6))
print(arr)
print(arr.dtype)

# print(dtype(arr))


[0 1 2 3 4 5]
int64


In [3]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

import numpy as np
arr = np.array([1.5, 2.6, 3.7])
if(arr.dtype == "float64"):
    print("Yes")
else:
    print("No")
print(arr.dtype)

Yes
float64


In [5]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

import numpy as np 
arr = np.array([1+2j, 3 + 4j, 5 + 6j], dtype = np.complex128)
print(arr)
print(arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
complex128


In [8]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np
arr_int = np.array([1, 2, 3, 4, 5, 6])
arr_float = arr_int.astype(np.float32)
print("Original array", arr_int, arr_int.dtype)
print("Converted array", arr_float, arr_float.dtype)


Original array [1 2 3 4 5 6] int64
Converted array [1. 2. 3. 4. 5. 6.] float32


In [9]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

import numpy as np
arr = np.array([3.141592653, 2.718281828, 1.618033988])
arr_float32 = arr.astype(np.float32)
print("Original array (float64):", arr, arr.dtype)
print("Converted array (float32):", arr_float32, arr_float32.dtype)


Original array (float64): [3.14159265 2.71828183 1.61803399] float64
Converted array (float32): [3.1415927 2.7182817 1.618034 ] float32


In [10]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

import numpy as np
def array_attributes(arr):
    attributes = {
    "shape": arr.shape,
    "size": arr.size,
    "data_type": arr.dtype
  }
    return attributes

arr = np.array([[1, 2], [4, 5]])
attributes = array_attributes(arr)
print(attributes)


{'shape': (2, 2), 'size': 4, 'data_type': dtype('int64')}


In [11]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

import numpy as np
def array_dimension(arr):
    dimension = arr.ndim
    return dimension

arr = np.array([[[1, 2], [3, 4], [5, 6]]])
print(array_dimension(arr))

3


In [12]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

import numpy as np
def item_size_info(arr):
    item_size = arr.dtype.itemsize  
    total_size = arr.size * item_size  

    info = {
      "item_size": item_size,
      "total_size": total_size
  }
    return info

arr = np.array([1, 2, 3, 4, 5]) 
size_info = item_size_info(arr)
print(size_info)



{'item_size': 8, 'total_size': 40}


In [60]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

import numpy as np
def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))

(12, 4)


In [65]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

import numpy as np
def shape_stride_relationship(arr):
    shape = arr.shape
    stride = arr.strides
    relationship = {
        "shape": shape,
        "stride": stride
    }
    return relationship
arr = np.array([[1, 2], [4, 5]])
print(shape_stride_relationship(arr))
    

{'shape': (2, 2), 'stride': (8, 4)}


In [30]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

import numpy as np
def create_zeros_array(n):
    return np.zeros(n) 

ans_11 = create_zeros_array(5)
print(ans_11)
    

[0. 0. 0. 0. 0.]


In [27]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
# NumPy array filled with ones of size `rows x cols`.

import numpy as np

def create_ones_matrix(rows, cols, dtype):
    return np.ones((rows, cols), dtype=dtype)

ones_matrix = create_ones_matrix(3, 4, dtype=np.int32)
print(ones_matrix)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy 
# array with a range starting from `start`, ending at stop (exclusive), and with the specified step.

import numpy as np

def generate_range_array(start, stop, step):
    ans_13 = np.array(range(start,stop, step))
    return ans_13

generate_range_array(1, 10, 2)

array([1, 3, 5, 7, 9])

In [42]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and 
# generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

import numpy as np

def generate_linear_space(start, stop, num):
    ans_14 = np.linspace(start, stop, num)
    return ans_14

generate_linear_space(0.0, 1.0, 10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [43]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of 
# size `n x n` using `numpy.eye`.

import numpy as np

def create_identity_matrix(n):
    return np.eye(n, n)

create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

import numpy as np

def convert_to_array(l):
    return np.array(l)

List = [1, 2, 3, "Jems", 4.0, 2, "S", 5]
convert_to_array(List)

array(['1', '2', '3', 'Jems', '4.0', '2', 'S', '5'], dtype='<U32')

In [48]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
print("Original Array:", original_array)

view_array = original_array.view()
print("View Array:", view_array)

view_array[0] = 99
print("Modified View Array:", view_array)
print("Original Array after modification through view:", original_array)

reshaped_view = view_array.view().reshape((5, 1))
print("Reshaped View Array:\n", reshaped_view)

reshaped_view[0, 0] = 100
print("Modified Reshaped View Array:\n", reshaped_view)
print("Original Array after modification through reshaped view:", original_array)


Original Array: [1 2 3 4 5]
View Array: [1 2 3 4 5]
Modified View Array: [99  2  3  4  5]
Original Array after modification through view: [99  2  3  4  5]
Reshaped View Array:
 [[99]
 [ 2]
 [ 3]
 [ 4]
 [ 5]]
Modified Reshaped View Array:
 [[100]
 [  2]
 [  3]
 [  4]
 [  5]]
Original Array after modification through reshaped view: [100   2   3   4   5]


In [71]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

import numpy as np

def concatenate_arrays(array1, array2, axis):
        concatenated_array = np.concatenate((array1, array2), axis=axis)
        return concatenated_array

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along the first axis (rows)
result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

# Concatenate along the second axis (columns)
result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 1:\n", result_axis_1)


Concatenated along axis 0:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along axis 1:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [74]:
# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy concatenate`.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

ans_19 = np.concatenate((arr1, arr2), axis = 1)
print(ans_19)

[[ 1  2  3  7  8  9 10]
 [ 4  5  6 11 12 13 14]]


In [82]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def vertical_concat(arrays):
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
array3 = np.array([[7, 8, 9]])

arrays = [array1, array2, array3]

ans_20 = vertical_concat(arrays)
print("Vertically Stacked array: \n", ans_20)


Vertically Stacked array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given 
# step size.

import numpy as np

def arr_range(start, stop, step):
    return np.array(range(start, stop + 1, step))

arr_range(1, 10, 2)


array([1, 3, 5, 7, 9])

In [87]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

import numpy as np

def arr_eqspaced(start, stop, step):
    array = np.linspace(start, stop, step)
    return array

arr_eqspaced(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [4]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

import numpy as np
def arr_log(start, stop, step):
    array = np.logspace(start, stop, step)
    return array

ans_23 = arr_log(0, 3, 5) # 10^0 = 1, 10^3 = 1000, 5
print(ans_23)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [18]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers 
# between 1 and 100.

import numpy as np
import pandas as pd

arr_24 = np.random.randint(1, 101, size = (5, 3))
print(arr_24)

df_24 = pd.DataFrame(arr_24)
df_24

[[54  7 92]
 [73 95 46]
 [39 85 94]
 [61  6 94]
 [78  4 21]]


0   1   2
0  54   7  92
1  73  95  46
2  39  85  94
3  61   6  94
4  78   4  21

In [22]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. 
# Use NumPy operations within the Pandas DataFrame.

import numpy as np
import pandas as pd

def negative_to_zero_replace(df_25, column_name):
    if column_name in df_25.columns:
        df_25[column_name] = np.where(df_25[column_name] < 0, 0, df_25[column_name])
    else:
        print("The column name you've entered is not exist")
        
    return df_25

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [10, 20, -30, 40, 50]
}
df_25 = pd.DataFrame(data)

print("Original dataframe is: \n", df_25)

ans_25 = negative_to_zero_replace(df_25, 'B')
print("Modified Dataframe is \n", ans_25)


Original dataframe is: 
    A  B   C
0  1 -1  10
1 -2  2  20
2  3 -3 -30
3 -4  4  40
4  5 -5  50
Modified Dataframe is 
    A  B   C
0  1  0  10
1 -2  2  20
2  3  0 -30
3 -4  4  40
4  5  0  50


In [23]:
# 26. Access the 3rd element from the given NumPy array.

import numpy as np
arr_26 = np.array([10, 20, 30, 40, 50])
print(arr_26[2])

30


In [27]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

import numpy as np
arr_27 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

ans_27 = arr_27[1, 2]
print(ans_27)

6


In [29]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

import numpy as np
arr_28 = np.array([3, 8, 2, 10, 5, 7])
ans_28 = arr_28[arr_28 > 5]
print(ans_28)


[ 8 10  7]


In [30]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

import numpy as np

arr_29 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr_29[2:6])

[3 4 5 6]


In [39]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

import numpy as np

arr_30 = np.array([[1, 2, 3],
                 [4, 5, 6], 
                 [7, 8, 9]])

ans_30 = arr_30[0:2, 1:3]
print(ans_30)

[[2 3]
 [5 6]]


In [43]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in 
# another array.

import numpy as np

def extract_elements(arr_31, indices):
    return arr_31[indices[:,0], indices[:,1]] 

arr_31 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

indices = np.array([
    [0, 1],
    [2, 2],
    [1, 0]
])

ans_31 = extract_elements(arr_31, indices)
print(ans_31) 


[2 9 4]


In [59]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

import numpy as np
def filter_elements(arr_32, temp):
    return arr_32[arr_32 > temp]

arr_32 = np.array([6, 12, 4, 1, 10, 9, 15, 13])
threshold = 9
ans_32 = filter_elements(arr_32, threshold)
print(ans_32)

[12 10 15 13]


In [18]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays 
#  for each dimension.

import numpy as np
def extract_3d(arr_33, indices):
    return arr_33[indices[0], indices[1], indices[2]]

arr_33 = np.arange(27).reshape(3, 3, 3)

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])

ans_33 = extract_3d(arr_33, (x_indices, y_indices, z_indices))
print(ans_33)


[ 5 10 24]


In [26]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

import numpy as np

def two_condition(arr, condition_1, condition_2):
    return arr[(condition_1) & (condition_2)]

arr_34 = np.array([-4, -2, -5, 1, 4, 5, 2, -6, 8, 9])

condition_1 = arr_34 > 1
condition_2 = arr_34 <= 8
ans_34 = two_condition(arr_34, condition_1, condition_2)
print(ans_34)

[4 5 2 8]


In [30]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

import numpy as np

def extract_2d(arr, indices):
    return arr[indices[0], indices[1]]

arr_35 = np.arange(9).reshape(3, 3)

row_indices = np.array([1, 2, 1])
col_indices = np.array([0, 2, 1])

print(arr_35)
ans_35 = extract_2d(arr_35, (row_indices, col_indices))
print("Extracted Elements are:", ans_35)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Extracted Elements are: [3 8 4]


In [34]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

import numpy as np

arr_36 = np.arange(9).reshape(3, 3)
print("Original Array: \n", arr_36)
print("Broadcasted Array: \n", arr_36 + 5)

Original Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Broadcasted Array: 
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [38]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element 
# in arr1 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

arr1 = arr1.reshape(3, 1)
ans_37 = arr2 * arr1
print(ans_37)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [46]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

arr1 = arr1.reshape(4, 1)
ans_38 = arr1 + arr2
print(ans_38)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [50]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

import numpy as np

arr1 = np.array([[1], [2], [3]]) 
arr2 = np.array([[10, 20, 30]]) 

ans_39 = arr1 + arr2
print(ans_39)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [71]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. 
#  Handle the shape incompatibility.

import numpy as np

arr1 = np.array([[1, 2, 3], 
                [4, 5, 6]])

arr2 = np.array([[7, 8], 
                [9, 10]])

arr2_expanded = arr2[:, np.newaxis, :]

ans_40 = arr1[:, :, np.newaxis] * arr2_expanded
print(ans_40)

[[[ 7  8]
  [14 16]
  [21 24]]

 [[36 40]
  [45 50]
  [54 60]]]


In [73]:
# 41. Calculate column-wise mean for the given array:

import numpy as np
arr_41 = np.array([[1, 2, 3], [4, 5, 6]])

ans_41 = np.mean(arr_41, axis = 0)
print(ans_41)

[2.5 3.5 4.5]


In [74]:
# 42. Find maximum value in each row of the given array:

import numpy as np
arr_42 = np.array([[1, 2, 3], [4, 5, 6]])

ans_42 = np.max(arr_42, axis = 1)
print(ans_42)


[3 6]


In [75]:
# 43. For the given array, find indices of maximum value in each column.

import numpy as np

arr_43 = arr = np.array([[1, 2, 3], [4, 5, 6]])

ans_43 = np.argmax(arr_42, axis = 0)
print(ans_43)

[1 1 1]


In [30]:
# 44. For the given array, apply custom function to calculate moving sum along rows

import numpy as np

def moving_sum_along_rows(arr, windows_size):
    rows, col = arr.shape
    moving_sum = np.zeros((rows, col - windows_size + 1))
    
    for i in range(rows):
        for j in range(col - windows_size + 1):
            moving_sum[i, j] = np.sum(arr[i, j:j + windows_size])
    return moving_sum

arr_44 = np.array([[1, 2, 3], [4, 5, 6]])
windows_size = 2
ans_44 = moving_sum_along_rows(arr_44, windows_size)
print(ans_44)


[[ 3.  5.]
 [ 9. 11.]]


In [38]:
# 45. In the given array, check if all elements in each column are even.

import numpy as np

def iseven(arr):
    return np.all(arr % 2 == 0, axis = 0).all()
    
arr_45 = np.array([[2, 4, 6], [3, 5, 7]])
ans_45 = iseven(arr_45)
print(ans_45)

False


In [39]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

import numpy as np

def reshape_arr(arr, m, n):
    return arr.reshape(m, n)

arr_46 = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3

ans_46 = reshape_arr(arr_46, m, n)
print(ans_46)



[[1 2 3]
 [4 5 6]]


In [45]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

import numpy as np

def flattened(arr):
    return arr.flatten()

arr_47 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array befor flatten \n", arr_47)
ans_47 = flattened(arr_47)
print("Array after flatten \n", ans_47)

Array befor flatten 
 [[1 2 3]
 [4 5 6]]
Array after flatten 
 [1 2 3 4 5 6]


In [55]:
# 48. Write a function that concatenates two given arrays along a specified axis.

import numpy as np

def concatenate(arr1, arr2):
    return np.concatenate((arr1, arr2), axis = 1)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

ans_48 = concatenate(array1, array2)
print(ans_48)

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

import numpy as np

def split_arr(arr):
    return np.split(arr, [1], axis = 0)

arr_49 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ans_49 = split_arr(arr_49)
print(ans_49)

[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]])]


In [76]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

import numpy as np 

def insert_delete(arr, values, index, deletion_index):
    arr = np.insert(arr, index, values)
    print("Array after inserting values \n", arr)
    arr = np.delete(arr, deletion_index)
    print("Array after deleting values \n", arr)
    return arr

arr_50 = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11] 
indices_to_delete = [1, 3]

ans_50 = insert_delete(arr_50, values_to_insert, indices_to_insert, indices_to_delete)
print("Final Modified array \n", ans_50)


Array after inserting values 
 [ 1  2 10  3  4 11  5]
Array after deleting values 
 [ 1 10  4 11  5]
Final Modified array 
 [ 1 10  4 11  5]


In [6]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
# Perform element-wise addition between `arr1` and `arr2`.

import numpy as np

arr1 = np.random.randint(1, 21, size=10)  
arr2 = np.arange(1, 11)

print("Array1 \n", arr1)
print("Array2 \n", arr2)
ans_51 = arr1 + arr2
print("Element wise addition \n", ans_51)



Array1 
 [10  2 15  1 11  3  9  9 10  9]
Array2 
 [ 1  2  3  4  5  6  7  8  9 10]
Element wise addition 
 [11  4 18  5 16  9 16 17 19 19]


In [10]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

print("Array 1 \n", arr1)
print("Array 2 \n", arr2)
ans_52 = arr2 - arr1
print("Subtracted Array \n" , ans_52)

Array 1 
 [10  9  8  7  6  5  4  3  2  1]
Array 2 
 [ 1  2  3  4  5  6  7  8  9 10]
Subtracted Array 
 [-9 -7 -5 -3 -1  1  3  5  7  9]


In [7]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
# Perform element-wise multiplication between `arr1` and `arr2`.

import numpy as np

arr1 = np.random.randint(1, 20, size = 5)
arr2 = np.arange(1, 6)
ans_53 = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise multiplication:", ans_53)

Array 1: [13 18  4  4 13]
Array 2: [1 2 3 4 5]
Element-wise multiplication: [13 36 12 16 65]


In [9]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. 
# Perform element-wise division of `arr1` by `arr2`.

import numpy as np

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6, 1)
ans_54 = arr1 / arr2

print("Array1 :", arr1)
print("Array2 :", arr2)
print("Resulting Array :", ans_54)


Array1 : [ 2  4  6  8 10]
Array2 : [1 2 3 4 5]
Resulting Array : [2. 2. 2. 2. 2.]


In [10]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. 
# Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

import numpy as np

arr1 = np.arange(1, 6, 1)
arr2 = np.arange(5, 0, -1)

ans_55 = arr1 ** arr2
print("Array1 :", arr1)
print("Array2 :", arr2)
print("Resultant Array :", ans_55)


Array1 : [1 2 3 4 5]
Array2 : [5 4 3 2 1]
Resultant Array : [ 1 16 27 16  5]


In [24]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

import numpy as np

def occurrence_string(arr, substring):
    count = np.char.count(arr, substring)
    return count
    
arr_56 = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = "hello"
ans_56 = occurrence_string(arr_56, substring)
print("Occurrence of a substring :", ans_56)
print("Count of occurrences of a substring :", ans_56.sum())


Occurrence of a substring : [1 0 1 0 1]
Count of occurrences of a substring : 3


In [27]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 
import numpy as np

def extract_uppercase(arr):
    extract = lambda x: ''.join([char for char in x if char.isupper()])
    vectorized_extract = np.vectorize(extract)
    return vectorized_extract(arr)

arr_57 = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr_57)
print(result) 


['H' 'W' 'OAI' 'GPT']


In [6]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

import numpy as np

def replace_substring(arr, old_substring, new_substring):
    replace = lambda x : x.replace(old_substring, new_substring)
    ans = np.vectorize(replace)
    return ans(arr)

arr_58 = np.array(['apple', 'banana', 'grape', 'pineapple'])
ans_58 = replace_substring(arr_58, "apple", "fruit")
print("Original Array: ", arr_58)
print("Resultant Array: ", ans_58)

Original Array:  ['apple' 'banana' 'grape' 'pineapple']
Resultant Array:  ['fruit' 'banana' 'grape' 'pinefruit']


In [7]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

import numpy as np

def concatenate_string(Array1, Array2):
    return Array1 + Array2 
#   return np.char.add(Array1, Array2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

ans_59 = concatenate_string(arr1, arr2)
print("Concatenated String :", ans_59)

Concatenated String : ['HelloOpen' 'WorldAI']


In [16]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
 
import numpy as np

def longest_string(arr):
    length = np.vectorize(len)(arr)
    return max(length)
    
arr_60 = np.array(['apple', 'banana', 'grape', 'pineapple'])
ans_60 = longest_string(arr_60)
print(ans_60)


9


In [25]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
# standard deviation of the dataset using NumPy's functions.

import numpy as np
import pandas as pd

data = np.random.randint(1, 1001, size=100)

mean = np.mean(df)
median = np.median(df)
variance = np.var(df)
std_dev = np.std(df)

df = pd.DataFrame(data)
print(df)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)




      0
0   475
1   497
2   607
3   484
4    53
..  ...
95  492
96  181
97  453
98   33
99   42

[100 rows x 1 columns]
Mean: 500.63
Median: 507.5
Variance: 0    75970.9731
dtype: float64
Standard Deviation: 0    275.628324
dtype: float64


C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\numpy\_core\fromnumeric.py:4006: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)
C:\Users\ASUS\AppData\Roaming\Python\Python39\site-packages\numpy\_core\fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


In [30]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np
import pandas as pd

data = np.random.randint(1, 100, size = 50)
df_62 = pd.DataFrame(data)

df_62.describe()




0
count  50.000000
mean   50.300000
std    27.797555
min     4.000000
25%    24.000000
50%    46.500000
75%    73.750000
max    96.000000

In [31]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
# arrays using NumPy's `corrcoef` function.

import numpy as np

arr1 = np.random.randn(100)
arr2 = arr1 * 2 + np.random.randn(100)

ans_63 = np.corrcoef(arr1, arr2)[0, 1]
print(ans_63)

0.8610770128070988


In [36]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

import numpy as np

arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(4, 2))

ans_64 = np.dot(arr1, arr2)
print("Array1 :\n", arr1)
print("Array2 :\n", arr2)
print("Array after matrix multiplication :\n", ans_64)

Array1 :
 [[4 6 1 7]
 [8 2 4 2]
 [2 3 6 5]]
Array2 :
 [[4 4]
 [6 8]
 [4 2]
 [7 8]]
Array after matrix multiplication :
 [[105 122]
 [ 74  72]
 [ 85  84]]


In [40]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
# percentiles along with the first and third quartiles.

import numpy as np

data = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  
percentile_90 = np.percentile(data, 90)

# Calculate first and third quartiles (25th and 75th percentiles)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)

print("10th Percentile:", percentile_10)
print("Median (50th Percentile):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", q1)
print("Third Quartile (Q3):", q3)


10th Percentile: 150.20000000000002
Median (50th Percentile): 614.0
90th Percentile: 919.7
First Quartile (Q1): 280.25
Third Quartile (Q3): 815.75


In [51]:
# 66. Create a NumPy array of integers and find the index of a specific element.

import numpy as np

arr = np.array([10, 25, 32, 18, 45, 5])

index = np.where(arr == 32)[0][0]

print("Index of 32:", index)



Index of 32: 2


In [57]:
# 67. Generate a random NumPy array and sort it in ascending order.

import numpy as np

data = np.random.randint(1, 50, size = 25)
print("Original Array: ", data)
ans_67 = np.sort(data)
print("Sorted Array: ", ans_67)

Original Array:  [47 23  4 45 41  8 11 30 11 42 24 38 44 12 45 47 23 34 40 29 22 40 30 32
 49]
Sorted Array:  [ 4  8 11 11 12 22 23 23 24 29 30 30 32 34 38 40 40 41 42 44 45 45 47 47
 49]


In [60]:
# 68. Filter elements >20  in the given NumPy array.

import numpy as np

arr_68 = np.array([12, 25, 6, 42, 8, 30])
ans_68 = arr_68[arr_68 > 20]
print(ans_68)

[25 42 30]


In [63]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

import numpy as np

arr_69 = np.array([1, 5, 8, 12, 15])
ans_69 = arr_69[arr_69 % 3 == 0]
print(ans_69)

[12 15]


In [69]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

import numpy as np

arr_70 = np.array([10, 20, 30, 40, 50])
ans_70 = arr_70[(arr_70 >= 20) & (arr_70 <= 40)]
print(ans_70)

[20 30 40]


In [72]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

import numpy as np

arr_71 = np.array([1, 2, 3])
ans_71 = arr_71.dtype.byteorder
print(ans_71)

=


In [2]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

import numpy as np

arr_72 = np.array([1, 2, 3], dtype=np.int32)
print("Original Array:", arr_72)
arr_72.byteswap(inplace = True)
print("Array after byte swapping: ", arr_72)

Original Array: [1 2 3]
Array after byte swapping:  [16777216 33554432 50331648]


In [9]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

import numpy as np

arr_73 = np.array([1, 2, 3], dtype=np.int32)
new_arr_73 = arr_73.view(arr_73.dtype.newbyteorder())   # AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead
print("Original Array: ", arr_73)
print("Resultant Array: ", new_arr_73)

Original Array:  [1 2 3]
Resultant Array:  [16777216 33554432 50331648]


In [12]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

import numpy as np

arr_74 = np.array([1, 2, 3], dtype=np.int32)

if np.little_endian:
    new_arr = arr_74.view(arr_74.dtype.newbyteorder('>'))
else:
    new_arr = arr_74.view(arr_74.dtype.newbyteorder('<'))
    
print("Original Array: ", arr_74)
print("Resulltant Array: ", new_arr)

Original Array:  [1 2 3]
Resulltant Array:  [16777216 33554432 50331648]


In [13]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

import numpy as np

arr_75 = np.array([1, 2, 3], dtype=np.int32)
is_little_endian = arr.dtype.byteorder == '<'

print("System is little-endian:", is_little_endian)


System is little-endian: False


In [14]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [100   2   3   4   5   6   7   8   9  10]


In [33]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

import numpy as np

arr_77 = np.random.randint(1, 51, size = (3, 3))
print("Original Array: \n", arr_77)

view_slice = arr_77[1:, 1:]
print("Sliced Array: \n", view_slice)

view_slice[0, 0] = 99
print("Modified Sliced Array:\n", view_slice)
print("Finalized Original Array: \n", arr_77)

Original Array: 
 [[41 24 12]
 [38 47 41]
 [33 46 38]]
Sliced Array: 
 [[47 41]
 [46 38]]
Modified Sliced Array:
 [[99 41]
 [46 38]]
Finalized Original Array: 
 [[41 24 12]
 [38 99 41]
 [33 46 38]]


In [31]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

import numpy as np

arr_a = np.array([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print("Original Array: \n", arr_a)

view_b = arr_a[1:, 1:]
print("Sliced Array: \n", view_b)
add = view_b + 5
print("Finalized Array: \n", add)

print("Final Original Array: \n", arr_a)

Original Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Sliced Array: 
 [[ 5  6]
 [ 8  9]
 [11 12]]
Finalized Array: 
 [[10 11]
 [13 14]
 [16 17]]
Final Original Array: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
# reflects changes in the original `orig_array`.

import numpy as np

arr_79 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print("Original Array: \n", arr_79)

reshaped_view = arr_79.reshape(4, 2)
print("Reshaped Array: \n", reshaped_view)

reshaped_view[1, 1] = 60
print("Modified Reshaped Array: \n", reshaped_view)

print("Final Original Array: \n", arr_79)




Original Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped Array: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modified Reshaped Array: 
 [[ 1  2]
 [ 3 60]
 [ 5  6]
 [ 7  8]]
Final Original Array: 
 [[ 1  2  3 60]
 [ 5  6  7  8]]


In [38]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. 
# Modify an element in `data_copy` and verify if it affects the original `data`.

import numpy as np

arr_80 = np.random.randint(1, 50, size = (3, 4))
print("Original Array: \n", arr_80)

data_copy = arr_80[arr_80 > 5]
print("Data copy: \n", data_copy)

data_copy[0] = 100
print("Modified data copy: \n", data_copy)
print("Final original Array: \n", arr_80)

Original Array: 
 [[ 2 27 33 19]
 [28 24 15 22]
 [ 9 18 25  8]]
Data copy: 
 [27 33 19 28 24 15 22  9 18 25  8]
Modified data copy: 
 [100  33  19  28  24  15  22   9  18  25   8]
Final original Array: 
 [[ 2 27 33 19]
 [28 24 15 22]
 [ 9 18 25  8]]


In [39]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

import numpy as np

matrix_A = np.random.randint(1, 51, size = (3, 3))
matrix_B = np.random.randint(1, 51, size = (3, 3))

print("Matrix A: \n", matrix_A)
print("Matrix B: \n", matrix_B)

print("Addition of matrices: \n", matrix_A + matrix_B)
print("Subtraction of matrices: \n", matrix_A - matrix_B)

Matrix A: 
 [[18 18 34]
 [13 29 11]
 [26 28 47]]
Matrix B: 
 [[11 30 26]
 [28 35 11]
 [ 5 24 28]]
Addition of matrices: 
 [[29 48 60]
 [41 64 22]
 [31 52 75]]
Subtraction of matrices: 
 [[  7 -12   8]
 [-15  -6   0]
 [ 21   4  19]]


In [41]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

import numpy as np

C = np.random.randint(1, 10, size = (3, 2))
D = np.random.randint(1, 10, size = (2, 4))

print("Matrix C: \n", C)
print("Matrix D: \n", D)

print("Multiplication of Matrices: \n", np.dot(C, D))

Matrix C: 
 [[6 3]
 [7 8]
 [9 8]]
Matrix D: 
 [[3 6 8 3]
 [6 7 8 7]]
Multiplication of Matrices: 
 [[ 36  57  72  39]
 [ 69  98 120  77]
 [ 75 110 136  83]]


In [42]:
# 83. Create a matrix `E` and find its transpose.

import numpy as np

E = np.random.randint(1, 21, size = (3, 2))
print("Matrix E: \n", E)

print("Transpose of Array: \n", E.transpose())

Matrix E: 
 [[20 17]
 [16  5]
 [19  9]]
Transpose of Array: 
 [[20 16 19]
 [17  5  9]]


In [46]:
# 84. Generate a square matrix `F` and compute its determinant.

import numpy as np

F = np.random.randint(1, 5, size = (3, 3))
print("Matrix F: \n", F)

print("Determinant of matrix F: ", np.linalg.det(F))

Matrix F: 
 [[1 4 1]
 [1 4 3]
 [3 4 2]]
Determinant of matrix F:  16.000000000000007


In [50]:
# 85. Create a square matrix `G` and find its inverse.

import numpy as np

G = np.random.randint(1, 10, size=(3, 3))

G_inverse = np.linalg.inv(G)

print("Matrix G:\n", G)
print("Inverse of G:\n", G_inverse)


Matrix G:
 [[1 2 5]
 [9 9 2]
 [1 4 9]]
Inverse of G:
 [[ 1.46  0.04 -0.82]
 [-1.58  0.08  0.86]
 [ 0.54 -0.04 -0.18]]
